### ISSUE TITLE
make

### ISSUE THREAD

**Issue by bhcqzf** [icesky1stm/wrktcp#1]

**Comment by bhcqzf** [comment]
make之后报了个这个错误
求解，不懂c语言

CC src/wrktcp.c
CC src/net.c
CC src/aprintf.c
CC src/stats.c
CC src/units.c
CC src/ae.c
CC src/zmalloc.c
CC src/islog.c
CC src/tcpini.c
src/tcpini.c: In function ‘tcpini_fit’:
src/tcpini.c:193:9: warning: implicit declaration of function ‘strcasestr’ [-Wimplicit-function-declaration]
         if( strcasestr(tcpini->req_head, "Host") == NULL){
         ^
src/tcpini.c:193:50: warning: comparison between pointer and integer [enabled by default]
         if( strcasestr(tcpini->req_head, "Host") == NULL){
                                                  ^
src/tcpini.c:202:60: warning: comparison between pointer and integer [enabled by default]
         if( strcasestr(tcpini->req_head, "Content-Length") == NULL){
                                                            ^
CC src/istime.c
src/istime.c: In function ‘nolocks_localtime’:
src/istime.c:100:10: error: ‘timezone’ undeclared (first use in this function)
     t -= timezone;                      /* Adjust for timezone. */
          ^
src/istime.c:100:10: note: each undeclared identifier is reported only once for each function it appears in
make: *** [obj/istime.o] Error 1

**Comment by icesky1stm** [comment]
是什么系统和版本，我适配一下timezone的获取方式。

**Comment by icesky1stm** [comment]
> 是什么系统和版本，我适配一下timezone的获取方式。



> 是什么系统和版本，我适配一下timezone的获取方式。



> make之后报了个这个错误
> 求解，不懂c语言
> 
> CC src/wrktcp.c
> CC src/net.c
> CC src/aprintf.c
> CC src/stats.c
> CC src/units.c
> CC src/ae.c
> CC src/zmalloc.c
> CC src/islog.c
> CC src/tcpini.c
> src/tcpini.c: In function ‘tcpini_fit’:
> src/tcpini.c:193:9: warning: implicit declaration of function ‘strcasestr’ [-Wimplicit-function-declaration]
> if( strcasestr(tcpini->req_head, "Host") == NULL){
> ^
> src/tcpini.c:193:50: warning: comparison between pointer and integer [enabled by default]
> if( strcasestr(tcpini->req_head, "Host") == NULL){
> ^
> src/tcpini.c:202:60: warning: comparison between pointer and integer [enabled by default]
> if( strcasestr(tcpini->req_head, "Content-Length") == NULL){
> ^
> CC src/istime.c
> src/istime.c: In function ‘nolocks_localtime’:
> src/istime.c💯10: error: ‘timezone’ undeclared (first use in this function)
> t -= timezone; /* Adjust for timezone. */
> ^
> src/istime.c💯10: note: each undeclared identifier is reported only once for each function it appears in
> make: *** [obj/istime.o] Error 1

另外建议用gitee的本项目仓库，github我这边的ip被污染了，公司最近比较严格翻墙不太方便。

**Comment by bhcqzf** [comment]
linux系统的centos7，项目本身是在gitee上clone的，感谢大佬给我回复

**Comment by icesky1stm** [comment]
已经修复，有空可以试一下。

**Comment by bhcqzf** [comment]
十分感谢
